### ISSUE TITLE
tutorial link is broken

### ISSUE THREAD

**Issue by AhmedArslan** [MoseleyBioinformaticsLab/GOcats#12]

**Comment by hunter-moseley** [comment]
Can you be more specific where the link is?
The tutorial link in the README.rst works.

**Comment by ehinderer** [comment]
Hi Ahmed, 

On my end the documentation links work. Tutorials are provided in the documentation on readthedocs. There's a hyperlink in the README.rst, just under the big logo that will take you there (clicking logo will also). Here's the direct link for your convenience:
https://gocats.readthedocs.io/en/latest/tutorial.html#

Is this what you're referring to? If not, I'll be happy to help you with specifics.
