### ISSUE TITLE
Need to update the CITATION file

### ISSUE THREAD

**Issue by hunter-moseley** [MoseleyBioinformaticsLab/GOcats#21]
Eugene,

The CITATION file needs to be updated to include your two GOcats publications.

Warm regards,
Hunter

**Comment by hunter-moseley** [comment]
Should move to a CITATION.cff file.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by ehinderer** [comment]
Thanks for pointing that out! I'll add it to my todo list this week

cheers!
